- name: Mongodb
  hosts: localhost
  tasks:
  - name: copying
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongo.repo
  - name: install mangodb
    ansible.builtin.yum:
     name: mongodb
     state: installed
  - name: start and enable the service
    ansible.builtin.service:
     name: mongod
     state: started
     enabled: yes
  - name: replace 127.0.0.1 with 0.0.0.0
    ansible.builtin.replace:
     path: /etc/mongod.conf
     regex: 127.0.0.1
     replace: 0.0.0.0
  - name: restart the service
    ansible.builtin.service:
     name: mongod
     state: restarted
     
     